baseURL = 'http://daprtools.github.io/'
languageCode = 'en-us'
title = 'DaprDesigner'
contentDir = "content/en"

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false


[params]
    
    [params.footer]
        copyright = "©:2025: RKVS Raman. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"


    [params.social]
        github = "daprtools"    
  
